blank_issues_enabled: true
contact_links:
  - name: Pingvincoin Core Security Policy
    url: https://github.com/pingvincoin/pingvincoin/blob/master/SECURITY.md
    about: View security policy
  - name: Pingvincoin Core Developers
    url: https://pingvincoincore.org
    about: Pingvincoin Core homepage
